#ifndef __COMMANDS_H__
#define __COMMANDS_H__

#include <string.h>


#define INCORRECT_COMMAND_NO 0

#define IP_SET_COMMAND "ip"
#define IP_SET_COMMAND_NO 1
#define IP_SET_COMMAND_LEN strlen(IP_SET_COMMAND)

#define GW_SET_COMMAND "gw"
#define GW_SET_COMMAND_NO 2
#define GW_SET_COMMAND_LEN strlen(GW_SET_COMMAND)

#define NETMASK_SET_COMMAND "netmask"
#define NETMASK_SET_COMMAND_NO 3
#define NETMASK_SET_COMMAND_LEN strlen(NETMASK_SET_COMMAND)

#define SSID_SET_COMMAND "ssid"
#define SSID_SET_COMMAND_NO 4
#define SSID_SET_COMMAND_LEN strlen(SSID_SET_COMMAND)

#define PASS_SET_COMMAND "pass"
#define PASS_SET_COMMAND_NO 5
#define PASS_SET_COMMAND_LEN strlen(PASS_SET_COMMAND)

#define STATIC_IP_SET_COMMAND "static"
#define STATIC_IP_SET_COMMAND_NO 6
#define STATIC_IP_SET_COMMAND_LEN strlen(STATIC_IP_SET_COMMAND)

#define DYNAMIC_IP_SET_COMMAND "dynamic"
#define DYNAMIC_IP_SET_COMMAND_NO 7
#define DYNAMIC_IP_SET_COMMAND_LEN strlen(DYNAMIC_IP_SET_COMMAND)

#define SAVE_COMMAND "save"
#define SAVE_COMMAND_NO 8
#define SAVE_COMMAND_LEN strlen(SAVE_COMMAND)

#define HELP_COMMAND "help"
#define HELP_COMMAND_NO 9
#define HELP_COMMAND_LEN strlen(HELP_COMMAND)

#define EXIT_COMMAND "exit"
#define EXIT_COMMAND_NO 10
#define EXIT_COMMAND_LEN strlen(EXIT_COMMAND)

#define DISPLAY_CURRENT_COMMAND "dispay_current"
#define DISPLAY_CURRENT_COMMAND_NO 11
#define DISPLAY_CURRENT_COMMAND_LEN strlen(DISPLAY_CURRENT_COMMAND)

#define DISPLAY_SAVED_COMMAND "dispay_saved"
#define DISPLAY_SAVED_COMMAND_NO 12
#define DISPLAY_SAVED_COMMAND_LEN strlen(DISPLAY_SAVED_COMMAND)

#endif